export const dataShopping = [
    {
        title: "經典薯條套餐1",
        engTitle: "Classic Package 1",
        price: 120,
        count: 0,
        isDiscount: true,
        discountOff:0.7,
    },
    {
        title: "經典漢堡套餐2",
        engTitle: "Classic Package 2",
        price: 160,
        count: 0,
        isDiscount: true,
        discountOff:0.69,
    },
    {
        title: "經典漢堡套餐3",
        engTitle: "Classic Package 3",
        price: 110,
        count: 0,
        isDiscount: false,
        discountOff:1,
    },
    {
        title: "經典薯條套餐4",
        engTitle: "Classic Package 4",
        price: 120,
        count: 0,
        isDiscount: false,
        discountOff:1,
    },
    {
        title: "經典漢堡套餐5",
        engTitle: "Classic Package 5",
        price: 180,
        count: 0,
        isDiscount: false,
        discountOff:1,
    },
    {
        title: "經典漢堡套餐6",
        engTitle: "Classic Package 6",
        price: 170,
        count: 0,
        isDiscount: false,
        discountOff:1,
    },
    {
        title: "經典薯條套餐7",
        engTitle: "Classic Package 7",
        price: 160,
        count: 0,
        isDiscount: false,
        discountOff:1,
    },
    {
        title: "經典薯條套餐8",
        engTitle: "Classic Package 8",
        price: 150,
        count: 0,
        isDiscount: false,
        discountOff:1,
    },
    {
        title: "經典漢堡套餐9",
        engTitle: "Classic Package 9",
        price: 130,
        count: 0,
        isDiscount: false,
        discountOff:1,
    },
    {
        title: "經典漢堡套餐10",
        engTitle: "Classic Package 10",
        price: 180,
        count: 0,
        isDiscount: false,
        discountOff:1,
    },
    {
        title: "經典漢堡套餐11",
        engTitle: "Classic Package 11",
        price: 170,
        count: 0,
        isDiscount: false,
        discountOff:1,
    },
    {
        title: "經典漢堡套餐12",
        engTitle: "Classic Package 12",
        price: 130,
        count: 0,
        isDiscount: false,
        discountOff:1,
    },
];